name: Build and Test API

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'src/api/**'
      - 'tests/api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/api/JAT.XModuleManager.Api/JAT.XModuleManager.Api.csproj

    - name: Build
      run: dotnet build src/api/JAT.XModuleManager.Api/JAT.XModuleManager.Api.csproj --no-restore --configuration Release

    - name: Test
      run: dotnet test tests/JAT.XModuleManager.UnitTests/JAT.XModuleManager.UnitTests.csproj --no-build --configuration Release --verbosity normal